### ISSUE TITLE
Set of available languages is not automatically set

### ISSUE THREAD

**Issue by aarppe** [divvun/divvun-installer-macos#28]
When I install the new DivvunInstaller, I do not automatically get to the window with North-American and European languages listed out. I need to select 'Divvun Languages' at the top for this to happen.

<img width="649" alt="image" src="https://user-images.githubusercontent.com/15003407/83902694-1ade8380-a71a-11ea-8d96-99002963d3ae.png">

**Comment by bbqsrc** [comment]
Hi @aarppe, didn't expect to see you here this early. 😄 

I haven't implemented the list that you discussed with @snomos yet, that will happen before Monday morning.

**Comment by bbqsrc** [comment]
Also if he didn't tell you, you should change the channel to 'Nightly' in the settings.

**Comment by aarppe** [comment]
@bbqsrc Sjur asked me to report this as an issue, so I did. And yes, I've been advised to use the 'Nightly' option.

**Comment by bbqsrc** [comment]
Web app has been updated! Closing.
